# Generated by Django 5.2.13 on 2026-05-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Участие в событии', 'verbose_name_plural': 'Участия в событиях'},
        ),
        migrations.AlterModelOptions(
            name='seasonevent',
            options={'ordering': ['start_date'], 'verbose_name': 'Сезонное событие', 'verbose_name_plural': 'Сезонные события'},
        ),
    ]
