# Generated by Django 5.2.13 on 2026-05-14 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_achievement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seasonevent',
            options={'verbose_name': 'Сезонное событие', 'verbose_name_plural': 'Сезонные события'},
        ),
        migrations.AddField(
            model_name='cat',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.CreateModel(
            name='CatLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='cats.cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('cat', 'user')},
            },
        ),
    ]
